name: Deploy

on:
  push:
    branches:
      - main 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # More info: https://github.com/akhileshns/heroku-deploy
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "awp-exam-project-alex"
          heroku_email: "alexlind@outlook.dk"
